=== NewcastleRSE/health-literacy-logic-app/problemSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Problem",
    "definitions": {
        "Problem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "alert-block": {
                    "type": "object",
                    "items": {
                        "type": "object",
                        "alert-type": {
                            "anyOf": [
                                {
                                    "enum": [
                                        "note",
                                        "tip",
                                        "warning",
                                        "danger"
                                    ]
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "alert-title": {
                            "type": "string"
                        },
                        "alert-content": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "alert-type",
                        "alert-title",
                        "alert-content"
                    ]
                },
                "level": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Section"
                    }
                }
            },
            "required": [
                "icon",
                "id",
                "long-title",
                "sections",
                "short-title"
            ],
            "title": "Problem"
        },
        "Section": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SectionContent"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "Section"
        },
        "PurpleContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FluffyContent"
                    }
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "project-email": {
                    "type": "string"
                }
            },
            "required": [
                "content-type"
            ],
            "title": "PurpleContent"
        },
        "FluffyContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ContentContentUnion"
                    }
                },
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                }
            },
            "required": [
                "content",
                "content-type"
            ],
            "title": "FluffyContent"
        },
        "TentacledContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "TentacledContent"
        },
        "SectionContent": {
            "anyOf": [
                {
                    "$ref": "#/definitions/PurpleContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "SectionContent"
        },
        "ContentContentUnion": {
            "anyOf": [
                {
                    "$ref": "#/definitions/TentacledContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ContentContentUnion"
        },
        "ContentType": {
            "type": "string",
            "enum": [
                "list",
                "subsection"
            ],
            "title": "ContentType"
        }
    }
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/teachers-health-literacy.json
{
    "id": "teachers-health-literacy",
    "short-title": "Teachers health literacy",
    "long-title": "Teachers and social workers not trained in health literacy",
    "alert-block": {
        "alert-type": "note",
        "alert-title": "Section under development",
        "alert-content": "If you would like to add your ideas please use [this form](http://example.com)"
    },
    "level": "system",
    "icon": "teacher, school, educator, classroom, instructor.svg",
    "sections": [
        {
            "short-title": "heading",
            "long-title": "What is the level being targeted?",
            "content-type": "section-choice",
            "content": [
                {
                    "choice-option": "Individual level",
                    "choice-subtitle": "Things that happen between individuals, like one-to-one support or care",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Teachers",
                                "Social workers"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "System level",
                    "choice-subtitle": "Big system-wide things, like national policies or data systems",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "The Teaching Regulation Agency (TRA)",
                                "The Social Work Regulation Authority (Social Work England)"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "There is poor awareness of the need for health literacy in training for teaching and social work professionals"
                            ]
                        },
                        {
                            "short-title": "help",
                            "long-title": "What would help to solve the problem?",
                            "content-type": "list",
                            "content": [
                                "Government guidance for regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "actions",
                            "long-title": "What actions are involved in doing something about this?",
                            "content-type": "list",
                            "content": [
                                "Talking with the government about the problem",
                                "Change in government policy",
                                "Talking with regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Writing policy briefs about the issues",
                                "Meeting with key people (e.g. ministers, civil servants, regulatory bodies)"
                            ]
                        },
                        {
                            "short-title": "action-outcome",
                            "long-title": "What do we expect to come out of these actions?",
                            "content-type": "list",
                            "content": [
                                "Health literacy training will be embedded in teaching and social work professional training"
                            ]
                        },
                        {
                            "short-title": "change-marker",
                            "long-title": "How will we know things have changed?",
                            "content-type": "list",
                            "content": [
                                "Health literacy appears in teaching and social work training"
                            ]
                        },
                        {
                            "short-title": "short-term-change",
                            "long-title": "What will have changed in 1 year?",
                            "content-type": "list",
                            "content": [
                                "Policy brief will be given to ministers"
                            ]
                        },
                        {
                            "short-title": "long-term-change",
                            "long-title": "What will have happened in 3 years?",
                            "content-type": "list",
                            "content": [
                                "More teaching and public health professions will be starting to learn about health literacy as they train"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/health-professionals-literacy.json
{
    "id": "health-professionals-literacy",
    "short-title": "Health professionals literacy",
    "long-title": "Health and public health professionals are not trained in health literacy",
    "subtitle": "this is an example [subtitle](http://example.com)",
    "alert-block": {
        "alert-type": "note",
        "alert-title": "This is an alert title",
        "alert-content": "This is an alert content with a [potential link](http://example.com)"
    },
    "level": "system",
    "icon": "039-medical history.svg",
    "sections": [
        {
            "short-title": "heading",
            "long-title": "What is the level being targeted?",
            "content-type": "section-choice",
            "content": [
                {
                    "choice-option": "Individual level",
                    "choice-subtitle": "Things that happen between individuals, like one-to-one support or care",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Health professionals",
                                "patients, carers and the public"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Health professionals do not realise how important health literacy is for health outcomes"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "Organisation level",
                    "choice-subtitle": "Things that happen in organisations or communities, like teamwork or service coordination",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Training providers",
                                "Universities",
                                "Health professionals"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Training providers and universities do not include health literacy in their curricula for health professionals"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Meeting with key people (e.g. ministers, civil servants, regulatory bodies)"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "System level",
                    "choice-subtitle": "Big system-wide things, like national policies or data systems",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Regulatory bodies like the General Medical Council (GMC) and Nursing and Midwifery Council (NMC)"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Regulatory bodies and national standards do not require health literacy training"
                            ]
                        },
                        {
                            "short-title": "help",
                            "long-title": "What would help to solve the problem?",
                            "content-type": "list",
                            "content": [
                                "Government guidance for regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "actions",
                            "long-title": "What actions are involved in doing something about this?",
                            "content-type": "list",
                            "content": [
                                "Talking with the government about the problem",
                                "Change in government policy",
                                "Talking with regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Writing policy briefs"
                            ]
                        },
                        {
                            "short-title": "action-outcome",
                            "long-title": "What do we expect to come out of these actions?",
                            "content-type": "list",
                            "content": [
                                "Health literacy training will be embedded in health and public health professional training"
                            ]
                        },
                        {
                            "short-title": "change-marker",
                            "long-title": "How will we know things have changed?",
                            "content-type": "list",
                            "content": [
                                "Health literacy will appear in health and public health training"
                            ]
                        },
                        {
                            "short-title": "short-term-change",
                            "long-title": "What will have changed in 1 year?",
                            "content-type": "list",
                            "content": [
                                "Policy brief to ministers"
                            ]
                        },
                        {
                            "short-title": "long-term-change",
                            "long-title": "What will have happened in 3 years?",
                            "content-type": "list",
                            "content": [
                                "More health and public health professions will be starting to learn about health literacy as they train"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/different-vocabulary.json
{
    "id": "different-vocabulary",
    "short-title": "Different vocabulary",
    "long-title": "Different systems (like health and social services) use different words for things",
    "level": "system",
    "icon": "alphabet, literacy, letters, language, basics.svg",
    "sections": [
        {
            "short-title": "people-involved",
            "long-title": "Who should be involved?",
            "content-type": "list",
            "content": [
                "People who run the different systems"
            ]
        },
        {
            "short-title": "causes",
            "long-title": "What are the causes of the problem?",
            "content-type": "list",
            "content": [
                "A range of different words used by different people",
                "Systems that do not talk to each other",
                "Systems that are not joined up"
            ]
        },
        {
            "short-title": "help",
            "long-title": "What would help? ",
            "content-type": "list",
            "content": [
                "everyone using the same words",
                "using words that are easy to understand",
                "making sure letters to patients and the public are easy to understand",
                "letting people tell us when words are too complex",
                "systems that can be changed if needed",
                "staff training",
                "good policies",
                "good systems"
            ]
        },
        {
            "short-title": "actions",
            "long-title": "What actions are involved in doing something about this?",
            "content-type": "list",
            "content": [
                "talking with people using services",
                "knowing all the different words and what they mean",
                "agreeing on a common list of words across our region",
                "making sure these words are easy to understand",
                "making sure systems are in place to write information that is easy to understand and use simple words",
                "setting goals for meeting targets",
                "developing a role for facilitators"
            ]
        },
        {
            "short-title": "delivery",
            "long-title": "How will we deliver these actions?",
            "content-type": "list",
            "content": [
                "develop data systems that talk with each other",
                "develop a set of words that everyone agrees on",
                "make sure everyone knows what these words mean",
                "develop online and IT tools",
                "use Artificial Intelligence",
                "training courses on what words to use"
            ]
        },
        {
            "short-title": "action-outcome",
            "long-title": "What do we expect to come out of these actions?",
            "content-type": "list",
            "content": [
                "less use of acronyms",
                "clear languages used across systems",
                "more awareness of health literacy",
                "better understanding between systems",
                "better patient and public understanding of materials",
                "information that is more sensitive to different cultures"
            ]
        },
        {
            "short-title": "change-marker",
            "long-title": "How will we know things have changed?",
            "content-type": "list",
            "content": [
                "feedback from people who use the system",
                "random checks",
                "more different systems involved",
                "more organisations trained",
                "cost savings"
            ]
        },
        {
            "short-title": "short-term-change",
            "long-title": "What short term changes could we see?",
            "content-type": "list",
            "content": [
                "We will have action plans in place",
                "systems will work better for patients",
                "more organisations will be involved",
                "more materials will be re-written",
                "better use of resources"
            ]
        },
        {
            "short-title": "long-term-change",
            "long-title": "What do we think will happen in the longer term (3 years)? For example, increased health literacy, better disease control, improved health",
            "content-type": "list",
            "content": [
                "Information that is easier to understand",
                "systems using the same words as each other",
                "systems that are easier to use"
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}
